
DELETE http://localhost:3001/api/persons/1

### 
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

### 
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "大肌霸",
  "number": "666"
}
